_wandb:
    value:
        cli_version: 0.21.1
        code_path: code/train_custom.py
        e:
            4eufrbfhajytzicw4bw7x96hofc8d1r0:
                codePath: train_custom.py
                codePathLocal: train_custom.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1006447816704"
                        used: "98766630912"
                email: parkeh0724@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 5a60881ebf4055813c4b8e1029db4cc5d2c1e5b9
                    remote: https://github.com/acidify04/miniwob-plusplus.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-3a0449ef-6e37-2919-d5ed-03db0e423c3a
                host: cau-System-Product-Name
                memory:
                    total: "32751321088"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/cau/Documents/miniwob-plusplus/train_custom.py
                python: CPython 3.10.12
                root: /home/cau/Documents/miniwob-plusplus
                startedAt: "2025-08-14T10:08:46.845325Z"
                writerId: 4eufrbfhajytzicw4bw7x96hofc8d1r0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 49
            "2":
                - 1
                - 2
                - 3
                - 49
            "3":
                - 16
                - 35
            "4": 3.10.12
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
env_name:
    value: MiniWoBClickImageEnv
policy_type:
    value: CnnPolicy
total_timesteps:
    value: 10000
